version: "3.9"

services:
    db:
        image: postgres:17
        restart: unless-stopped
        environment:
            - POSTGRES_DB=botdb
            - POSTGRES_USER=botuser
            - POSTGRES_PASSWORD=botpass
        volumes:
            - pg_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U botuser -d botdb"]
            interval: 10s
            timeout: 5s
            retries: 5
        ports:
            # опционально: чтобы подключаться с хоста psql-клиентом
            - "5433:5432" # наружный порт/внутренний порт

    bot:
        build: .
        container_name: portfolio_bot
        restart: unless-stopped
        env_file: .env
        depends_on:
            db:
                condition: service_healthy
        # Прокидываем правильный PG_LINK внутрь контейнера
        environment:
            - PG_LINK=postgresql://botuser:botpass@db:5432/botdb
            - TZ=Europe/Moscow
        command: ["python", "run_bot.py"]

volumes:
    pg_data:
