version: "3.9"

services:
    db:
        image: postgres:17
        restart: unless-stopped
        # Берём учётные данные из .env.dev
        env_file: .env.dev
        environment:
            POSTGRES_DB: ${PG_DB}
            POSTGRES_USER: ${PG_USER}
            POSTGRES_PASSWORD: ${PG_PASSWORD}
        volumes:
            - pg_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}"]
            interval: 10s
            timeout: 5s
            retries: 5
        ports:
            # опционально: чтобы подключаться с хоста psql-клиентом
            - "5432:5432" # наружный порт/внутренний порт, 5432 по умолчанию для Postgres

    bot:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: example_bot_dev # изменить имя контейнера для другого проекта
        restart: unless-stopped
        # Используем специфичный env файл для dev
        env_file: .env.dev
        depends_on:
            db:
                condition: service_healthy
        # Прокидываем правильный PG_LINK внутрь контейнера
        environment:
            - PG_LINK=${PG_LINK}
            - TZ=${TZ}
        command: ["python", "run_bot.py"]

volumes:
    pg_data:
